### ISSUE TITLE
Misunderstanding about the feature "annotated links"   

### ISSUE THREAD

**Issue by Euler23333** [ahts4962/nav-link-header#1]
I am using your plugin, and it works properly. I can find the taskbar displayed at the top of my diary file tab. Regarding the annotated links feature, I have looked at the tips in the plugin, but I still don't quite understand how to use it. Here is my example:
![image](https://github.com/user-attachments/assets/dd38ca1e-b85f-485d-bfd6-4d06761a62b0)
![image](https://github.com/user-attachments/assets/32c01f7e-45cb-4cc1-be0f-5dfce4edf3ad)
This is a folder I created on how to design explosive strength training. I entered the text "vol." in the annotated links text box you provided. What modifications should I make?

**Comment by Euler23333** [comment]
我想知道我理解的注释字符串是否是可以不包括标题，但是可以被识别成反向链接？以及我的输入是否正确？
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/57d1e08f-b349-4b80-82f2-b642c00adde4">

**Comment by Euler23333** [comment]
I want to know if the comment string I understand can exclude the title but still be recognized as a backlink? And is my input correct?
![image](https://github.com/user-attachments/assets/5cff09c3-26e0-4107-aa2e-c063e7ba3a60)

**Comment by ahts4962** [comment]
I'm not quite sure about your use case. Is it correct that you want to add links to the index page, "vol.1...", and "vol.3..." at the top of the "vol.2..."?

In this case, you need to define some annotation strings first. For example, enter "◀️,🔼,▶️" in the Annotation strings field (I recommend using emojis). Then put "🔼" just before the link to "vol.2..." in the index page (more specifically, make sure "🔼[[vol.2...]]" is in the index page). Similarly, place "◀️" and "▶️" before [[vol.2...]] in "vol.1..." and "vol.3..." respectively. The resulting links will look like "◀️vol.1... 🔼(index page) ▶️vol.3..." (This plugin is not intended to make links to previous or next notes, so it may look a bit weird).

I'm sorry if I misunderstood your intentions.

**Comment by Euler23333** [comment]
okay i'll try it

**Comment by Euler23333** [comment]
> I'm not quite sure about your use case. Is it correct that you want to add links to the index page, "vol.1...", and "vol.3..." at the top of the "vol.2..."?
> 
It works!Thank you for your assistance!The function of your plugin have a useful convenience for me to navigate from continuous files like those I mentioned above!Here are the outcome:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/6ed22703-fb54-48de-9989-4c851b6979d9">
Thanks again for your help!
