### ISSUE TITLE
[FR] Create Hotkeys to adjacent notes

### ISSUE THREAD

**Issue by hyungtaecf** [ahts4962/nav-link-header#6]
I would like to set hotkeys to navigate between notes. Like "previous", "next" and "up".

So, if it is about daily notes, it would have a shortcut for yesterday, tomorrow and the next scope (week, month, quarter or year according to what is enabled in the configurations).

e.g. Let's say weekly notes are disabled but monthly notes are enabled, then the "up" shortcut would go to the current month. If you go to the month, then the shortcuts would be to the previous month, next month and the next scope and so on.

I'm not sure if this is the right plugin to request this feature, but I couldn't find a better place to request it.

**Comment by ahts4962** [comment]
Thank you for your suggestion.

It is reasonable to add such commands to this plugin since there is a situation like monthly note is enabled in periodic notes plugin but disabled in this plugin.

I have added commands for hotkeys, and released them in 1.0.5.
